<?php include("includes/header.php"); ?>

<div>
	<form method="post" action="/login">
	Login
	<input name="login" type="text"><br />
	Senha
	<input name="senha" type="password"><br />
	<input type="submit" value="Acessar" />
</form>
</div>
            
            
            <?php 
            
            foreach($view_lista as $valor){
            	
				echo $valor['name'];

            }
            
            
            ?>